title: Віталій Ковалишин
email: vitaly@kovalyshyn.pp.ua
description: >
  Персональний сайт Віталія Ковалишина про Linux, телефонію та життя.
  Vitaly Kovalyshyn - Linux, Call Centre, VoIP, Running and more...

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.kovalyshyn.pp.ua" # the base hostname & protocol for your site

show_downloads: false
google_analytics: 'UA-7767214-27'

# Handling Reading
exclude: ["README.md", "README.html"]

twitter_username: kovalyshyn
github_username:  kovalyshyn

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: jekyll-theme-midnight
plugins:
  - jekyll-feed

